export const red: string
export const pink: string
export const purple: string
export const violet: string
export const indigo: string
export const blue: string
export const lightBlue: string
export const cyan: string
export const teal: string
export const green: string
export const lightGreen: string
export const lime: string
export const yellow: string
export const amber: string
export const orange: string
export const deepOrange: string
export const brown: string
export const grey: string
export const blueGrey: string
export const greenGrey: string
