export const red: string
export const red50: string
export const red50TP: string
export const red100: string
export const red100TP: string
export const red200: string
export const red200TP: string
export const red300: string
export const red300TP: string
export const red400: string
export const red400TP: string
export const red500: string
export const red600: string
export const red700: string
export const red800: string
export const red900: string
export const redA100: string
export const redA200: string
export const redA400: string
export const redA700: string
export const pink: string
export const pink50: string
export const pink50TP: string
export const pink100: string
export const pink100TP: string
export const pink200: string
export const pink200TP: string
export const pink300: string
export const pink300TP: string
export const pink400: string
export const pink400TP: string
export const pink500: string
export const pink600: string
export const pink700: string
export const pink800: string
export const pink900: string
export const pinkA100: string
export const pinkA200: string
export const pinkA400: string
export const pinkA700: string
export const purple: string
export const purple50: string
export const purple50TP: string
export const purple100: string
export const purple100TP: string
export const purple200: string
export const purple200TP: string
export const purple300: string
export const purple300TP: string
export const purple400: string
export const purple400TP: string
export const purple500: string
export const purple600: string
export const purple700: string
export const purple800: string
export const purple900: string
export const purpleA100: string
export const purpleA200: string
export const purpleA400: string
export const purpleA700: string
export const violet: string
export const violet50: string
export const violet50TP: string
export const violet100: string
export const violet100TP: string
export const violet200: string
export const violet200TP: string
export const violet300: string
export const violet300TP: string
export const violet400: string
export const violet400TP: string
export const violet500: string
export const violet600: string
export const violet700: string
export const violet800: string
export const violet900: string
export const violetA100: string
export const violetA200: string
export const violetA400: string
export const violetA700: string
export const indigo: string
export const indigo50: string
export const indigo50TP: string
export const indigo100: string
export const indigo100TP: string
export const indigo200: string
export const indigo200TP: string
export const indigo300: string
export const indigo300TP: string
export const indigo400: string
export const indigo400TP: string
export const indigo500: string
export const indigo600: string
export const indigo700: string
export const indigo800: string
export const indigo900: string
export const indigoA100: string
export const indigoA200: string
export const indigoA400: string
export const indigoA700: string
export const blue: string
export const blue50: string
export const blue50TP: string
export const blue100: string
export const blue100TP: string
export const blue200: string
export const blue200TP: string
export const blue300: string
export const blue300TP: string
export const blue400: string
export const blue400TP: string
export const blue500: string
export const blue600: string
export const blue700: string
export const blue800: string
export const blue900: string
export const blueA100: string
export const blueA200: string
export const blueA400: string
export const blueA700: string
export const lightBlue: string
export const lightBlue50: string
export const lightBlue50TP: string
export const lightBlue100: string
export const lightBlue100TP: string
export const lightBlue200: string
export const lightBlue200TP: string
export const lightBlue300: string
export const lightBlue300TP: string
export const lightBlue400: string
export const lightBlue400TP: string
export const lightBlue500: string
export const lightBlue600: string
export const lightBlue700: string
export const lightBlue800: string
export const lightBlue900: string
export const lightBlueA100: string
export const lightBlueA200: string
export const lightBlueA400: string
export const lightBlueA700: string
export const cyan: string
export const cyan50: string
export const cyan50TP: string
export const cyan100: string
export const cyan100TP: string
export const cyan200: string
export const cyan200TP: string
export const cyan300: string
export const cyan300TP: string
export const cyan400: string
export const cyan400TP: string
export const cyan500: string
export const cyan600: string
export const cyan700: string
export const cyan800: string
export const cyan900: string
export const cyanA100: string
export const cyanA200: string
export const cyanA400: string
export const cyanA700: string
export const teal: string
export const teal50: string
export const teal50TP: string
export const teal100: string
export const teal100TP: string
export const teal200: string
export const teal200TP: string
export const teal300: string
export const teal300TP: string
export const teal400: string
export const teal400TP: string
export const teal500: string
export const teal600: string
export const teal700: string
export const teal800: string
export const teal900: string
export const tealA100: string
export const tealA200: string
export const tealA400: string
export const tealA700: string
export const green: string
export const green50: string
export const green50TP: string
export const green100: string
export const green100TP: string
export const green200: string
export const green200TP: string
export const green300: string
export const green300TP: string
export const green400: string
export const green400TP: string
export const green500: string
export const green600: string
export const green700: string
export const green800: string
export const green900: string
export const greenA100: string
export const greenA200: string
export const greenA400: string
export const greenA700: string
export const lightGreen: string
export const lightGreen50: string
export const lightGreen50TP: string
export const lightGreen100: string
export const lightGreen100TP: string
export const lightGreen200: string
export const lightGreen200TP: string
export const lightGreen300: string
export const lightGreen300TP: string
export const lightGreen400: string
export const lightGreen400TP: string
export const lightGreen500: string
export const lightGreen600: string
export const lightGreen700: string
export const lightGreen800: string
export const lightGreen900: string
export const lightGreenA100: string
export const lightGreenA200: string
export const lightGreenA400: string
export const lightGreenA700: string
export const lime: string
export const lime50: string
export const lime50TP: string
export const lime100: string
export const lime100TP: string
export const lime200: string
export const lime200TP: string
export const lime300: string
export const lime300TP: string
export const lime400: string
export const lime400TP: string
export const lime500: string
export const lime600: string
export const lime700: string
export const lime800: string
export const lime900: string
export const limeA100: string
export const limeA200: string
export const limeA400: string
export const limeA700: string
export const yellow: string
export const yellow50: string
export const yellow50TP: string
export const yellow100: string
export const yellow100TP: string
export const yellow200: string
export const yellow200TP: string
export const yellow300: string
export const yellow300TP: string
export const yellow400: string
export const yellow400TP: string
export const yellow500: string
export const yellow600: string
export const yellow700: string
export const yellow800: string
export const yellow900: string
export const yellowA100: string
export const yellowA200: string
export const yellowA400: string
export const yellowA700: string
export const amber: string
export const amber50: string
export const amber50TP: string
export const amber100: string
export const amber100TP: string
export const amber200: string
export const amber200TP: string
export const amber300: string
export const amber300TP: string
export const amber400: string
export const amber400TP: string
export const amber500: string
export const amber600: string
export const amber700: string
export const amber800: string
export const amber900: string
export const amberA100: string
export const amberA200: string
export const amberA400: string
export const amberA700: string
export const orange: string
export const orange50: string
export const orange50TP: string
export const orange100: string
export const orange100TP: string
export const orange200: string
export const orange200TP: string
export const orange300: string
export const orange300TP: string
export const orange400: string
export const orange400TP: string
export const orange500: string
export const orange600: string
export const orange700: string
export const orange800: string
export const orange900: string
export const orangeA100: string
export const orangeA200: string
export const orangeA400: string
export const orangeA700: string
export const deepOrange: string
export const deepOrange50: string
export const deepOrange50TP: string
export const deepOrange100: string
export const deepOrange100TP: string
export const deepOrange200: string
export const deepOrange200TP: string
export const deepOrange300: string
export const deepOrange300TP: string
export const deepOrange400: string
export const deepOrange400TP: string
export const deepOrange500: string
export const deepOrange600: string
export const deepOrange700: string
export const deepOrange800: string
export const deepOrange900: string
export const deepOrangeA100: string
export const deepOrangeA200: string
export const deepOrangeA400: string
export const deepOrangeA700: string
export const brown: string
export const brown50: string
export const brown50TP: string
export const brown100: string
export const brown100TP: string
export const brown200: string
export const brown200TP: string
export const brown300: string
export const brown300TP: string
export const brown400: string
export const brown400TP: string
export const brown500: string
export const brown600: string
export const brown700: string
export const brown800: string
export const brown900: string
export const brownA100: string
export const brownA200: string
export const brownA400: string
export const brownA700: string
export const grey: string
export const grey50: string
export const grey50TP: string
export const grey100: string
export const grey100TP: string
export const grey200: string
export const grey200TP: string
export const grey300: string
export const grey300TP: string
export const grey400: string
export const grey400TP: string
export const grey500: string
export const grey600: string
export const grey700: string
export const grey800: string
export const grey900: string
export const greyA100: string
export const greyA200: string
export const greyA400: string
export const greyA700: string
export const blueGrey: string
export const blueGrey50: string
export const blueGrey50TP: string
export const blueGrey100: string
export const blueGrey100TP: string
export const blueGrey200: string
export const blueGrey200TP: string
export const blueGrey300: string
export const blueGrey300TP: string
export const blueGrey400: string
export const blueGrey400TP: string
export const blueGrey500: string
export const blueGrey600: string
export const blueGrey700: string
export const blueGrey800: string
export const blueGrey900: string
export const blueGreyA100: string
export const blueGreyA200: string
export const blueGreyA400: string
export const blueGreyA700: string
export const greenGrey: string
export const greenGrey50: string
export const greenGrey50TP: string
export const greenGrey100: string
export const greenGrey100TP: string
export const greenGrey200: string
export const greenGrey200TP: string
export const greenGrey300: string
export const greenGrey300TP: string
export const greenGrey400: string
export const greenGrey400TP: string
export const greenGrey500: string
export const greenGrey600: string
export const greenGrey700: string
export const greenGrey800: string
export const greenGrey900: string
export const greenGreyA100: string
export const greenGreyA200: string
export const greenGreyA400: string
export const greenGreyA700: string
